//ContactList Actions
export const CONTACTLIST_GET_ALL = 'CONTACTLIST_REQUEST_GET_ALL';
export const CONTACTLIST_BEGIN_GET_ALL = 'CONTACTLIST_BEGIN_GET_ALL';
export const CONTACTLIST_RECEIVE_ALL = 'CONTACTLIST_RECEIVE_GET_ALL';

export const CONTACT_REQUEST_ONE = 'CONTACT_REQUEST_ONE';

//Contact Create
export const CONTACT_REQUEST_CREATE = 'CONTACT_REQUEST_CREATE';
export const CONTACT_BEGIN_CREATE = 'CONTACT_BEGIN_CREATE';
export const CONTACT_RESOLVE_CREATE = 'CONTACT_RESOLVE_CREATE';
export const CONTACT_RESET_STATUS = 'CONTACT_RESET_STATUS';
//Contact Update
export const CONTACT_REQUEST_UPDATE = 'CONTACT_REQUEST_UPDATE';
export const CONTACT_BEGIN_UPDATE = 'CONTACT_BEGIN_UPDATE';
export const CONTACT_RESOLVE_UPDATE = 'CONTACT_RESOLVE_UPDATE';

export const CONTACT_REQUEST_DELETE = 'CONTACT_REQUEST_DELETE';
export const CONTACT_THROW_ERROR = 'CONTACT_THROW_ERROR';
// export const CONTACT_CLEAR_ERROR = 'CONTACT_CLEAR_ERROR';


