//Interactions Action Types

//All Interactions for one user
export const INTERACTIONS_GET_ALL_FOR_USER ='INTERACTIONS_GET_ALL_FOR_USER';
export const INTERACTIONS_GET_ALL_FOR_USER_BEGIN = 'INTERACTIONS_GET_ALL_FOR_USER_BEGIN';
export const INTERACTIONS_GET_ALL_FOR_USER_RECEIVE = 'INTERACTIONS_GET_ALL_FOR_USER_RECEIVE';

//All interactions for one contact
export const INTERACTIONS_GET_ALL_FOR_CONTACT ='INTERACTIONS_GET_ALL_FOR_CONTACT';
export const INTERACTIONS_GET_ALL_FOR_CONTACT_BEGIN = 'INTERACTIONS_GET_ALL_FOR_CONTACT_BEGIN';
export const INTERACTIONS_GET_ALL_FOR_CONTACT_RECEIVE = 'INTERACTIONS_GET_ALL_FOR_CONTACT_RECEIVE';

//Get ONE interaction
export const INTERACTIONS_GET_ONE ='INTERACTIONS_GET_ONE';
export const INTERACTIONS_GET_ONE_BEGIN = 'INTERACTIONS_GET_ONE_BEGIN';
export const INTERACTIONS_GET_ONE_RECEIVE = 'INTERACTIONS_GET_ONE_RECEIVE';

//Delete ONE interaction
export const INTERACTIONS_DELETE ='INTERACTIONS_DELETE';
export const INTERACTIONS_DELETE_BEGIN = 'INTERACTIONS_DELETE_BEGIN';
export const INTERACTIONS_DELETE_RECEIVE = 'INTERACTIONS_DELETE_RECEIVE';

//Update interaction
export const INTERACTIONS_UPDATE ='INTERACTIONS_UPDATE';
export const INTERACTIONS_UPDATE_BEGIN = 'INTERACTIONS_UPDATE_BEGIN';
export const INTERACTIONS_UPDATE_RECEIVE = 'INTERACTIONS_UPDATE_RECEIVE';

export const INTERACTIONS_CREATE ='INTERACTIONS_CREATE';
export const INTERACTIONS_CREATE_BEGIN = 'INTERACTIONS_CREATE_BEGIN';
export const INTERACTIONS_CREATE_RECEIVE = 'INTERACTIONS_CREATE_RECEIVE';

export const INTERACTIONS_ERROR ='INTERACTIONS_ERROR';
export const INTERACTIONS_ERROR_CLEAR ='INTERACTIONS_ERROR_CLEAR';